/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import modeloConection.ConexaoBD;
import CModeloDaoMetodos.daoMedicos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import MmodeloBeansAtributos.BeansMedicos;
import MmodeloBeansAtributos.ModeloTabela;

/**
 *
 * @author Denilson
 */
public class CadMedicos extends javax.swing.JFrame {

    BeansMedicos medico = new BeansMedicos();
    daoMedicos dao = new daoMedicos();
    ConexaoBD conexao0 = new ConexaoBD();
    int flag = 0;

    public CadMedicos() {
        initComponents();
        preencherTabela("Select * from medicos order by nome_medico");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNomeMedico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboEsper = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCrm = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPesquisas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome");

        txtNomeMedico.setEnabled(false);
        txtNomeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMedicoActionPerformed(evt);
            }
        });

        jLabel4.setText("Espercialização");

        cboEsper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cirugião" }));
        cboEsper.setEnabled(false);
        cboEsper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEsperActionPerformed(evt);
            }
        });

        jLabel5.setText("CRM");

        txtCrm.setEnabled(false);

        tabelaPesquisas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaPesquisas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaPesquisas);

        jLabel3.setText("ID");

        txtId.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cboEsper, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelar)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(cboEsper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Médicos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel1))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(627, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboEsperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEsperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboEsperActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtNomeMedico.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo NOME para continuar!");
            //Para ir direto para o campo nome para o mais rapido ser preenchido
            txtNomeMedico.requestFocus();
        } else if (txtCrm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CRM para continuar!");
            txtCrm.requestFocus();
        } else 
            if (flag == 1) {
            medico.setNome(txtNomeMedico.getText());
            medico.setCrm(Integer.parseInt(txtCrm.getText()));
            medico.setEspercializacao(String.valueOf(cboEsper.getSelectedItem()));
            dao.Salvar(medico);
            txtNomeMedico.setText("");
            txtCrm.setText("");
            txtNomeMedico.setEnabled(false);
            txtCrm.setEnabled(false);
            cboEsper.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnCancelar.setEnabled(false);
            preencherTabela("select * from medicos order by nome_medico");
        } else {
            medico.setCodigo(Integer.parseInt(txtId.getText()));
            medico.setNome(txtNomeMedico.getText());
            medico.setCrm(Integer.parseInt(txtCrm.getText()));
            medico.setEspercializacao(String.valueOf(cboEsper.getSelectedItem()));
            dao.Editar(medico);
            txtId.setText("");
            txtNomeMedico.setText("");
            txtCrm.setText("");
            txtNomeMedico.setEnabled(false);
            txtCrm.setEnabled(false);
            cboEsper.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(false);
            preencherTabela("select * from medicos order by nome_medico");

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;
        txtNomeMedico.setEnabled(true);
        txtCrm.setEnabled(true);
        cboEsper.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtId.setText("");
        txtNomeMedico.setText("");
        txtCrm.setText("");
        txtPesquisa.setText("");
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtPesquisa.setEnabled(false);
        btnPesquisar.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        medico.setPesquisa(txtPesquisa.getText());
        BeansMedicos med = dao.buscarMedicos(medico);
        txtNomeMedico.setText(medico.getNome());
        txtId.setText(String.valueOf(medico.getCodigo()));
        txtCrm.setText(String.valueOf(medico.getCrm()));
        cboEsper.setSelectedItem(medico.getEspercializacao());
        //Para pesquisar com a letra digitada exemplo "a", vai trazer todos os registros que contem a latra "a"
        preencherTabela("select * from medicos where nome_medico like '%" + medico.getPesquisa() + "%'");
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtNomeMedico.setEnabled(false);
        txtCrm.setEnabled(false);
        cboEsper.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnNovo.setEnabled(true);
        btnEditar.setEnabled(false);
        btnCancelar.setEnabled(false);
        txtNomeMedico.setText("");
        txtCrm.setText("");
        txtPesquisa.setEnabled(true);
        btnPesquisar.setEnabled(true);
        txtId.setText("");
        txtNomeMedico.setText("");
        txtCrm.setText("");

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMedicoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        txtNomeMedico.setEnabled(true);
        txtCrm.setEnabled(true);
        cboEsper.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            medico.setCodigo(Integer.parseInt(txtId.getText()));
            dao.Excluir(medico);
            txtId.setText("");
            txtNomeMedico.setText("");
            txtCrm.setText("");
            txtNomeMedico.setEnabled(false);
            txtCrm.setEnabled(false);
            cboEsper.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(true);
            btnCancelar.setEnabled(false);
            btnEditar.setEnabled(false);
            btnExcluir.setEnabled(false);
            preencherTabela("select * from medicos order by nome_medico");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
//preencer os campos quando for selecionado
    private void tabelaPesquisasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisasMouseClicked
        String nome_medico = "" + tabelaPesquisas.getValueAt(tabelaPesquisas.getSelectedRow(), 1);
        conexao0.conexao();
        conexao0.executeSQL("select * from medicos where nome_medico = '" + nome_medico + "'");
        try {
            conexao0.rs.first();
            txtId.setText(String.valueOf(conexao0.rs.getInt("cod_medico")));
            txtNomeMedico.setText(conexao0.rs.getString("nome_medico"));
            txtCrm.setText(String.valueOf(conexao0.rs.getInt("crm_medico")));
            cboEsper.setSelectedItem(conexao0.rs.getString("espercializacao_medico"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados!" + ex);
        }
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }//GEN-LAST:event_tabelaPesquisasMouseClicked

    public void preencherTabela(String sql) {
        //Esta instanciando as listas para fazer as linhas da tabela
        ArrayList dados = new ArrayList();
        //Instanciando a String sendo que e um vetor
        //{} dentro das chaves vai ser o nome das colunas
        //Esta instanciando as colunas para fazer as colunas da tabela
        String[] colunas = new String[]{"ID", "Nome", "Espercialidade", "CRM"};
        //conexao0 e a instanciação da classe conexaoBD, e conexao e o metodo que está dentro dela que faz a conexão com o bd
        conexao0.conexao();
        //conexao0, é a conexao com o banco
        //Vai fazer a execução do codigo sql
        conexao0.executeSQL(sql);
        try {
            //vai pegar o primeiro resultado da conexao0
            conexao0.rs.first();
            do {//trazendo os campos do banco para a tabela
                dados.add(new Object[]{conexao0.rs.getInt("cod_medico"), conexao0.rs.getString("nome_medico"), conexao0.rs.getString("espercializacao_medico"), conexao0.rs.getInt("crm_medico")});
            }//Equanto estiver dados ele vai ficar percorrendo este registro, ele vai andar nas posicões pois não existe uma limitação e sim uma condição para ele percorrer tudo que ele achar
            while (conexao0.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Médico não cadastrado!\nPesquise por outro médico!");
        }
        //Dados a quantidade de linhas/ e colunas a quantidade de colunas
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tabelaPesquisas.setModel(modelo);
        //setPreferreWidth ela colocando o tamanho da tabela
        //getColumn(0) pq do (0)? pq a tabela começa do 0 como estamos trabalhado com um array ele começa da posição 0
        //getColumnModel é a coluna, getColumn e de onde vai começa a lista sendo que 0 e o ID e setPreferredWidth(23) é a lagura do campo id que vai receber os ids
        tabelaPesquisas.getColumnModel().getColumn(0).setPreferredWidth(30);
        //setResizable e para o usuario não poder mexer no tamanho dos camposda tabela com o mouse esticado-a
        tabelaPesquisas.getColumnModel().getColumn(0).setResizable(false);
        tabelaPesquisas.getColumnModel().getColumn(1).setPreferredWidth(180);
        tabelaPesquisas.getColumnModel().getColumn(1).setResizable(false);
        tabelaPesquisas.getColumnModel().getColumn(2).setPreferredWidth(80);
        tabelaPesquisas.getColumnModel().getColumn(2).setResizable(false);
        tabelaPesquisas.getColumnModel().getColumn(3).setPreferredWidth(80);
        tabelaPesquisas.getColumnModel().getColumn(3).setResizable(false);
        //Não vai poder reodenar o cabeçario
        tabelaPesquisas.getTableHeader().setReorderingAllowed(false);
        //O usuario não poderá redimecionar o tamanho da tabela
        tabelaPesquisas.setAutoResizeMode(tabelaPesquisas.AUTO_RESIZE_OFF);
        //Para o usuario poder somente selecionar um unico usuario da tabela por vez
        tabelaPesquisas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * / * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadMedicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboEsper;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaPesquisas;
    private javax.swing.JTextField txtCrm;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNomeMedico;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
