/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import CModeloDaoMetodos.daoUsuarios;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import MmodeloBeansAtributos.BeansUsuarios;
import MmodeloBeansAtributos.ModeloTabela;
import javax.swing.JLabel;
import javax.swing.JTable;
import modeloConection.ConexaoBD;

/**
 *
 * @author Denilson
 */
public class CadUsuario extends javax.swing.JFrame {

    BeansUsuarios usuario = new BeansUsuarios();
    daoUsuarios dao = new daoUsuarios();
    ConexaoBD conexao0 = new ConexaoBD();
    int flag = 0;

    public CadUsuario() {
        initComponents();
        preencherTabela("select * from usuarios order by usu_nome");
        //btnAlterar.setEnabled(false);
        //btnCancelar.setEnabled(false);
        //btnExcluir.setEnabled(false);
        //btnSalvar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtCSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        cboTipo = new javax.swing.JComboBox<>();
        btnNovo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Senha:");

        jLabel4.setText("Usuário:");

        jLabel5.setText("Confirmar Senha:");

        jLabel6.setText("Tipo:");

        txtUsuario.setEnabled(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtCSenha.setEnabled(false);
        txtCSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCSenhaActionPerformed(evt);
            }
        });

        txtSenha.setEnabled(false);

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "médico", "recepcionista" }));
        cboTipo.setEnabled(false);

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblUsuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblUsuarioAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblUsuario);

        jLabel2.setText("Cod:");

        txtCod.setEnabled(false);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnSalvar)
                                .addGap(24, 24, 24)
                                .addComponent(btnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addGap(75, 75, 75))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnNovo, btnSalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnNovo, btnSalvar});

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastro de Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(676, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtUsuario.setEnabled(!true);
        txtSenha.setEnabled(!true);
        txtCSenha.setEnabled(!true);
        cboTipo.setEnabled(!true);
        btnCancelar.setEnabled(!true);
        btnSalvar.setEnabled(!true);
        txtPesquisar.setEnabled(!false);
        btnBuscar.setEnabled(!false);
        btnNovo.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        //tblUsuario.setEnabled(false);
        txtCod.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");
        txtCSenha.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION) {
            usuario.setUsuCod(Integer.parseInt(txtCod.getText()));
            dao.Excluir(usuario);
            preencherTabela("select * from usuarios order by usu_nome");
            txtCod.setText("");
            txtUsuario.setText("");
            txtSenha.setText("");
            txtCSenha.setText("");
            btnAlterar.setEnabled(false);
            btnCancelar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnNovo.setEnabled(true);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCSenhaActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        flag = 1;
        txtUsuario.setEnabled(true);
        txtSenha.setEnabled(true);
        txtCSenha.setEnabled(true);
        cboTipo.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        txtPesquisar.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnNovo.setEnabled(false);
        //tblUsuario.setEnabled(false);
        txtCod.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");
        txtCSenha.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo USUÁRIO para continuar!");
            //Para ir direto para o campo nome para o mais rapido ser preenchido
            txtUsuario.requestFocus();
        } else if (txtSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo SENHA para continuar!");
            txtSenha.requestFocus();
        } else if (txtCSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo CONFIRMAR SENHA para continuar!");
            txtCSenha.requestFocus();
        } else if (txtSenha.getText().equals(txtCSenha.getText())) {
            if (flag == 1) {
                //usuario.setUsuCod(Integer.parseInt(txtCod.getText()));
                usuario.setUsuNome(txtUsuario.getText());
                usuario.setUsuSenha(txtSenha.getText());
                usuario.setUsuTipo(String.valueOf(cboTipo.getSelectedItem()));
                dao.Salvar(usuario);
                preencherTabela("select * from usuarios order by usu_nome");
                txtCod.setText("");
                txtUsuario.setText("");
                txtSenha.setText("");
                txtCSenha.setText("");
                txtUsuario.setEnabled(false);
                txtSenha.setEnabled(false);
                cboTipo.setEnabled(false);
                btnSalvar.setEnabled(false);
                txtCSenha.setEnabled(false);
                btnNovo.setEnabled(true);
                btnCancelar.setEnabled(false);
            } else {
                usuario.setUsuCod(Integer.parseInt(txtCod.getText()));
                usuario.setUsuNome(txtUsuario.getText());
                usuario.setUsuSenha(txtSenha.getText());
                usuario.setUsuTipo(String.valueOf(cboTipo.getSelectedItem()));
                dao.Alterar(usuario);
                preencherTabela("select * from usuarios order by usu_nome");
                txtCod.setText("");
                txtUsuario.setText("");
                txtSenha.setText("");
                txtCSenha.setText("");
                txtUsuario.setEnabled(false);
                txtSenha.setEnabled(false);
                cboTipo.setEnabled(false);
                btnSalvar.setEnabled(false);
                txtCSenha.setEnabled(false);
                btnNovo.setEnabled(true);
                btnCancelar.setEnabled(false);
                btnAlterar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Senhas não compativeis, Tente novamente!");
            txtCSenha.requestFocus();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        usuario.setUsuPesquisa(txtPesquisar.getText());
        BeansUsuarios bu = dao.buscarUsuario(usuario);
        txtCod.setText(String.valueOf(usuario.getUsuCod()));
        txtUsuario.setText(usuario.getUsuNome());
        txtSenha.setText(String.valueOf(usuario.getUsuSenha()));
        txtCSenha.setText(usuario.getUsuSenha());
        cboTipo.setSelectedItem(usuario.getUsuTipo());
        btnNovo.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        preencherTabela("select * from usuarios where usu_nome like '%" + usuario.getUsuPesquisa() + "%'");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        flag = 2;
        txtUsuario.setEnabled(true);
        txtSenha.setEnabled(true);
        txtCSenha.setEnabled(true);
        cboTipo.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tblUsuarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblUsuarioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblUsuarioAncestorAdded

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        String nome_usuario = "" + tblUsuario.getValueAt(tblUsuario.getSelectedRow(), 1);
        conexao0.conexao();
        conexao0.executeSQL("select * from usuarios where usu_nome = '" + nome_usuario + "'");
        try {
            conexao0.rs.first();
            txtCod.setText(String.valueOf(conexao0.rs.getInt("usu_cod")));
            txtUsuario.setText(conexao0.rs.getString("usu_nome"));
            txtSenha.setText(String.valueOf(conexao0.rs.getInt("usu_senha")));
            txtCSenha.setText(String.valueOf(conexao0.rs.getInt("usu_senha")));
            cboTipo.setSelectedItem(conexao0.rs.getString("usu_tipo"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados!" + ex);
        }
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnCancelar.setEnabled(true);
        txtCod.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtCSenha.setEnabled(false);
        txtSenha.setEnabled(false);
        cboTipo.setEnabled(false);
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void preencherTabela(String sql) {
        //Esta instanciando as listas para fazer as linhas da tabela
        ArrayList dados = new ArrayList();
        //Instanciando a String sendo que e um vetor
        //{} dentro das chaves vai ser o nome das colunas
        //Esta instanciando as colunas para fazer as colunas da tabela
        String[] colunas = new String[]{"ID", "Usuário", "Senha", "Tipo"};
        //conexao0 e a instanciação da classe conexaoBD, e conexao e o metodo que está dentro dela que faz a conexão com o bd
        conexao0.conexao();
        //conexao0, é a conexao com o banco
        //Vai fazer a execução do codigo sql
        conexao0.executeSQL(sql);
        try {
            //vai pegar o primeiro resultado da conexao0
            conexao0.rs.first();
            do {//trazendo os campos do banco para a tabela
                dados.add(new Object[]{conexao0.rs.getInt("usu_cod"), conexao0.rs.getString("usu_nome"), conexao0.rs.getString("usu_senha"), conexao0.rs.getString("usu_tipo")});
            }//Equanto estiver dados ele vai ficar percorrendo este registro, ele vai andar nas posicões pois não existe uma limitação e sim uma condição para ele percorrer tudo que ele achar
            while (conexao0.rs.next());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Usuário não cadastrado!\nPesquise por outro Usuário!");
        }
        //Dados a quantidade de linhas/ e colunas a quantidade de colunas
        ModeloTabela modelo = new ModeloTabela(dados, colunas);
        tblUsuario.setModel(modelo);
        //setPreferreWidth ela colocando o tamanho da tabela
        //getColumn(0) pq do (0)? pq a tabela começa do 0 como estamos trabalhado com um array ele começa da posição 0
        //getColumnModel é a coluna, getColumn e de onde vai começa a lista sendo que 0 e o ID e setPreferredWidth(23) é a lagura do campo id que vai receber os ids
        tblUsuario.getColumnModel().getColumn(0).setPreferredWidth(30);
        //setResizable e para o usuario não poder mexer no tamanho dos camposda tabela com o mouse esticado-a
        tblUsuario.getColumnModel().getColumn(0).setResizable(false);
        tblUsuario.getColumnModel().getColumn(1).setPreferredWidth(190);
        tblUsuario.getColumnModel().getColumn(1).setResizable(false);
        tblUsuario.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblUsuario.getColumnModel().getColumn(2).setResizable(false);
        tblUsuario.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblUsuario.getColumnModel().getColumn(3).setResizable(false);
        //Não vai poder reodenar o cabeçario
        tblUsuario.getTableHeader().setReorderingAllowed(false);
        //O usuario não poderá redimecionar o tamanho da tabela
        tblUsuario.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //Para o usuario poder somente selecionar um unico usuario da tabela por vez
        tblUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadMedicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JPasswordField txtCSenha;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
